### ISSUE TITLE
Array is passed to the Response::setRedirect as a second param (Gmail alias)

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_ReCaptcha#2]
Gmail alias is not supported when Object(MSP\\ReCaptcha\\Observer\\Frontend\\LoginObserver) is used.
### Preconditions:

1. Google API website key is valid and authorized for my domain
2. Google API secret key is valid and authorized for my domain
3. reCaptcha is enabled for frontend
4. reCaptcha type is 'Invisible reCaptcha'
5. "Use in login" is set to "Yes" in Stores > Settings > Configuration > Security Suite > Google ReCaptcha > Frontend
6. Magento CONFIG and FPC cache have valid state

### Steps to reproduce:

1. Go to /customer/account/create/
2. Fill in your details, but use something like this for email:
user.name@gmail.com
and remember the password.
3. Add product to cart and proceed to checkout.
4. Complete the order.
5. Log out
6. Go to /customer/account/create/
7. Fill in your details, but use something like this for email:
user.name+spam@gmail.com (more information can be found [here](https://support.google.com/mail/answer/22370?hl=en#alias))
8. Add product to cart and proceed to checkout.
9. Complete the order.
10. Log out
11. Go to /customer/account/login/
12. Use user.name@gmail.com as login and your password.

### Expected result:
:white_check_mark: I am able to log in.
### Actual result:
:x: In var/report/ folder:

```json
{"0":"Invalid HTTP response code","1":"#0 \/var\/www\/html\/tkhamlai\/pr\/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(219): Magento\\Framework\\HTTP\\PhpEnvironment\\Response->setHttpResponseCode(Array)\n#1 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/HTTP\/PhpEnvironment\/Response.php(119): Magento\\Framework\\App\\Response\\Http\\Interceptor->setHttpResponseCode(Array)\n#2 \/var\/www\/html\/tkhamlai\/pr\/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(206): Magento\\Framework\\HTTP\\PhpEnvironment\\Response->setRedirect('https:\/\/tsg.dev...', Array)\n#3 \/var\/www\/html\/tkhamlai\/pr\/app\/code\/MSP\/ReCaptcha\/Observer\/Frontend\/LoginObserver.php(108): Magento\\Framework\\App\\Response\\Http\\Interceptor->setRedirect('https:\/\/tsg.dev...', Array)\n#4 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/Event\/Invoker\/InvokerDefault.php(72): MSP\\ReCaptcha\\Observer\\Frontend\\LoginObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#5 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/Event\/Invoker\/InvokerDefault.php(60): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(MSP\\ReCaptcha\\Observer\\Frontend\\LoginObserver), Object(Magento\\Framework\\Event\\Observer))\n#6 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/Event\/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#7 \/var\/www\/html\/tkhamlai\/pr\/generated\/code\/Magento\/Framework\/Event\/Manager\/Proxy.php(95): Magento\\Framework\\Event\\Manager->dispatch('controller_acti...', Array)\n#8 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/App\/Action\/Action.php(99): Magento\\Framework\\Event\\Manager\\Proxy->dispatch('controller_acti...', Array)\n#9 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Customer\\Controller\\Account\\LoginPost\\Interceptor->___callParent('dispatch', Array)\n#11 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Customer\\Controller\\Account\\LoginPost\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/var\/www\/html\/tkhamlai\/pr\/generated\/code\/Magento\/Customer\/Controller\/Account\/LoginPost\/Interceptor.php(39): Magento\\Customer\\Controller\\Account\\LoginPost\\Interceptor->___callPlugins('dispatch', Array, Array)\n#13 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/App\/FrontController.php(55): Magento\\Customer\\Controller\\Account\\LoginPost\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#14 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#15 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#16 \/var\/www\/html\/tkhamlai\/pr\/app\/code\/Magento\/Store\/App\/FrontController\/Plugin\/RequestPreprocessor.php(94): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#17 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(135): Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#18 \/var\/www\/html\/tkhamlai\/pr\/app\/code\/Magento\/PageCache\/Model\/App\/FrontController\/BuiltinPlugin.php(73): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#19 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#20 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#21 \/var\/www\/html\/tkhamlai\/pr\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#22 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#23 \/var\/www\/html\/tkhamlai\/pr\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#24 \/var\/www\/html\/tkhamlai\/pr\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#25 {main}","url":"\/tkhamlai\/pr\/customer\/account\/loginPost\/","script_name":"\/tkhamlai\/pr\/index.php"}
```

**Comment by phoenix128** [comment]
This is a ducplicate issue of #3 .
